Adds additional guidelines around large contributions.
corda/corda-docs pull request #202
Opened 2020-08-18 10:04 UTC by joeldudleyr3

2020-08-19 16:39 UTC, taylorharvey-r3 requested changes
I've added a few suggestions regarding wording and list formatting.

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It significantly increases the project’s QA or support costs
```suggestion
* It would significantly increase the project’s QA or support costs.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It would require users to modify or recompile their CorDapps
```suggestion
* It would require users to modify or recompile their CorDapps.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It would introduce a new user-facing feature or configuration option
```suggestion
* It would introduce a new user-facing feature or configuration option.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It would introduce a new user-facing feature or configuration option
```suggestion
* It would introduce a new user-facing feature or configuration option.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It would negatively impact performance or security (e.g. by introducing a new dependency)
```suggestion
* It would negatively impact performance or security (e.g. by introducing a new dependency).
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +* It would take a long time to implement - two weeks or more
```suggestion
* It would take a long time to implement - two weeks or more.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +1. Raise a discussion of your proposed contribution on the [corda-dev mailing list](https://groups.io/g/corda-dev)
```suggestion
1. Raise a discussion of your proposed contribution on the [corda-dev mailing list](https://groups.io/g/corda-dev).
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * Please search the [mailing list archives](https://groups.io/g/corda-dev/topics) first for similar proposals that may have been discussed and declined in the past
```suggestion
    * Please search the [mailing list archives](https://groups.io/g/corda-dev/topics) first for similar proposals that may have been discussed and declined in the past.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * You will need to provide evidence that you are capable of delivering a large change to the platform. This can be done by contributing smaller changes to Corda first, or by otherwise showing you
```suggestion
    * You will need to provide evidence that you are capable of delivering a large change to the platform. This can be done by contributing smaller changes to Corda first, or by otherwise showing your ability and commitment to delivering large changes to complex, established projects.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +2. The project maintainers will feed back on your proposal. Some of the criteria they will be evaluating the proposal against are:
```suggestion
2. The project maintainers will feed back on your proposal. Some of the criteria they will be evaluating the proposal against include:
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * Whether the contribution is aligned with Corda’s mission statement (as outlined in the [Corda Introductory Whitepaper](https://docs.corda.net/en/pdf/corda-introductory-whitepaper.pdf))
```suggestion
    * The contribution is/is not aligned with Corda’s mission statement (as outlined in the [Corda Introductory Whitepaper](https://docs.corda.net/en/pdf/corda-introductory-whitepaper.pdf)).
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * Whether the contribution will negatively impact the ability of R3 and other project contributors to deliver improvements to the platform
```suggestion
    * The contribution will/will not negatively impact the ability of R3 and other project contributors to deliver improvements to the platform.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * Whether the contribution will require the project maintainers to have access to proprietary hardware or software resources
```suggestion
    * The contribution will/will not require the project maintainers to have access to proprietary hardware or software resources.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +    * The contribution’s impact on the project’s QA or support costs
```suggestion
    * The contribution’s impact on the project’s QA or support costs.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +3. If the proposal is accepted, please raise a design PR on the [Corda GitHub project](https://github.com/corda/corda). The design should give the rationale for the change, how the change will be imp
```suggestion
3. If the proposal is accepted, please raise a design PR on the [Corda GitHub project](https://github.com/corda/corda). The design should give the rationale for the change, how the change will be implemented, and what alternative designs were rejected. The engineering team will review your design and indicate any required changes.
```

2020-08-19 16:39 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.5/contributing.md
> +4. Once the design is approved, please go ahead with the change according to the [guidelines for small and medium contributions](contributing.md#making-the-required-changes). In addition to those gui
```suggestion
4. Once the design is approved, please go ahead with the change according to the [guidelines for small and medium contributions](contributing.md#making-the-required-changes). In addition to those guidelines, we require that large contributions be fully exercised by tests, including any exception paths and error handling.
```

2020-08-20 06:50 UTC, joeldudleyr3 commented
@taylorharvey-r3 Thanks Taylor. Addressed the comments.

2020-08-25 11:23 UTC, taylorharvey-r3 approved these changes

2020-08-25 11:28 UTC, merged