EG-3732: Fix reference node.conf, correct forward-looking statement, cross-link to node naming docs
corda/corda-docs pull request #211
Opened 2020-09-04 09:24 UTC by joeldudleyr3

2020-09-04 09:49 UTC, joeldudleyr3 commented
@ivanterziev-r3 I've noticed I've failed to reflect the same changes on the identical node.conf pages under the `Corda Operations and Deployment` section. Do you need me to make the changes there as well?

2020-09-05 08:34 UTC, ivanterziev-r3 approved these changes
LGTM

2020-09-05 08:56 UTC, ivanterziev-r3 requested changes

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.5/corda-configuration-fields.md
> +  The name must be a valid X.500 distinguished name, as per the [node naming constraints](node-naming.md).
Should we also change the sentence in line 281: 
Longer term these keys will be managed in secure hardware devices.** 
to
Alternatively, these keys can be managed in secure hardware devices.**

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
> +Alternatively, these keys can be managed in secure hardware devices.**
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-fields.md
> +The name must be a valid X.500 distinguished name, as per the [node naming constraints](node-naming.md).
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-fields.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +    "myLegalName" : "MYLEGALNAME",
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +    },
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +        }
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-05 08:56 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/setup/corda-configuration-file.md
> +    },
Same change needs made in:
`../content/en/docs/corda-enterprise/4.5/operations/deployment/corda-configuration-file.md`

2020-09-09 11:34 UTC, joeldudleyr3 commented
@ivanterziev-r3 Addressed.

2020-09-11 08:05 UTC, ivanterziev-r3 approved these changes
LGTM

2020-09-11 08:15 UTC, merged