added instalation instructions
corda/corda-docs pull request #314
Opened 2020-11-12 17:25 UTC by benpesterr3

2020-11-12 18:17 UTC, ivanterziev-r3 requested changes
A few suggestions added to the OS file - pls propagate to the CE file.

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +* BNE workflows https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-workflows/1.0/business-networks-workflows-1.0.jar
```suggestion
* BNE workflows: [https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-workflows/1.0/business-networks-workflows-1.0.jar](https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-workflows/1.0/business-networks-workflows-1.0.jar).
```

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +* Sample CorDapp contracts https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-contracts/1.0/business-networks-demo-contracts
```suggestion
* Sample CorDapp contracts: [https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-contracts/1.0/business-networks-demo-contracts-1.0.jar](https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-contracts/1.0/business-networks-demo-contracts-1.0.jar).
```

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +* Sample CorDapp workflows https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-workflows/1.0/business-networks-demo-workflows
```suggestion
* Sample CorDapp workflows: [https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-workflows/1.0/business-networks-demo-workflows-1.0.jar](https://software.r3.com/artifactory/webapp/#/artifacts/browse/tree/General/corda-releases/net/corda/bn/business-networks-demo-workflows/1.0/business-networks-demo-workflows-1.0.jar).
```

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +1. Add the business-networks-contracts dependency in your **contracts** (and states) cordapp module:
```suggestion
1. Add the `business-networks-contracts` dependency in your **contracts** (and states) CorDapp module:
```

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +2. Add the business-networks-workflows dependency in your "workflows" cordapp module:
```suggestion
2. Add the `business-networks-workflows` dependency in your **workflows** CorDapp module:
```

2020-11-12 18:17 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/business-network-membership.md
> +You have installed the business network membership extension.
```suggestion
You have installed the Business Network membership extension.
```

2020-11-16 14:31 UTC, tubibuto approved these changes
Looks good, let's wait also for @bpaunescu's sanity check.

2020-11-19 09:53 UTC, ivanterziev-r3 approved these changes
LGTM

2020-11-19 12:53 UTC, bpaunescu approved these changes
Thank you @benpesterr3 , this looks really good.

2020-11-19 13:19 UTC, merged