payments docs added
corda/corda-docs pull request #377
Opened 2020-12-24 15:00 UTC by benpesterr3

menu reorganised - apps = reference apps.

For review only - decisions pending on: 

* Name for Payments CorDapp development status. Have used 'Pre-Alpha' but many options remain open. 
* Menu structure regarding Reference (or experimental) apps. 
* Engineering team review of the context - are we sending the right message to customers - ie. Use this, but don't spend money without talking to us. 
* Contact us link and name required for these docs to be complete, so need advice on who that is. 

Much of this work will be completed once Docs team are together on Jan 4th.

2021-01-04 16:02 UTC, edward-prosser commented on content/en/docs/apps/payments/_index.md
> +# Payments and ModulR CorDapps Pre-alpha
Judging by their website it's "Modulr" with a lower-case r. Also, should `Pre-alpha` is capitalised differently in the left hand many than in this title. I suspect it should probably read `pre-alpha` unless it's part of name.

2021-01-05 09:46 UTC, phil-r3 requested changes
Looks good Ben.  I could only spot two small things.

2021-01-05 09:46 UTC, phil-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `PaymentExecutionException` - This exception will be thrown if the currency specified is not `GBP`.
A new payment type was recently added. It now accepts GBP and EUR.

2021-01-05 09:46 UTC, phil-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +5. The modulr-payments-cordapp waits for a response from the Modulr API.
It doesn't wait, it polls.  It polls the status of the payment and returns when it is in a final state of PROCESSED or CANCELLED.

2021-01-05 09:54 UTC, phil-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `PaymentExecutionException` - This exception will be thrown if the currency specified is not `GBP`.
A new payment type was added recently.  It now accepts GBP and EUR.

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +Use these steps to get an overview of how you can integrate a PSP with your network. You can choose to create your own solution with a PSP of your choice, or follow these steps using the [Mock Paymen
```suggestion
Use these steps to get an overview of how you can integrate a PSP with your network. You can choose to create your own solution with a PSP of your choice, or follow these steps using the [Mock Payment Rail](#mock-payment-rail) which includes a mock PSP that acts in a similar way to most commercial PSPs, but will not incur costs. For early and experimental purposes, the Mock Payment Rail gives you a fast, easy to set up experience of making payments on Corda.
```

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +'''
I presume the ''' is necessary?

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `mock-payment-service-provider` - a test PSP that allows payments to be made int he mock environment.
```suggestion
* `payments-core` - provides the standard API and deals with messages in the ISO 20022 messaging Standard, and Integration layer (cordapp that communicates with PSP), which converts the standard ISO messages into PSP specific formats and handle communication and authorization with the specific PSP.  
* `external-action-manager` - used to manage and store asynchronous operations that occur outside of your network - like initiating payment via a PSP.
* `iso-xml-utils` - used to marshall and unmarshall raw XML into ISO 20022. ISO 20022 is the international messaging standard used by PSPs globally.
* `mock-payment-rail` - a test payment rail that allows you to quickly build and deploy a trial payment solution.
* `mock-payment-service-provider` - a test PSP that allows payments to be made in the mock environment.
```

Pet peeve, can these be in the order they appear afterwards?

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +Actions that can be performed using the `external-action-manager` are either **idempotent** or **non-idempotent**.  An action is idempotent when you want a specific operation to be executed once, no
Is 'deduplication' the right word here?

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +These actions are triggered during a flow when a node needs to make a HTTP request via the client for the PSP's API.  In the case of `MockPaymentRail`, the actions are triggered when a flow needs to
```suggestion
These actions are triggered during a flow when a node needs to make an HTTP request via the client for the PSP's API.  In the case of `MockPaymentRail`, the actions are triggered when a flow needs to make an asynchronous request using `MockRailClient`.  When an action is being executed during a flow, the flow is check-pointed and serialized to disk.
```

2021-01-05 13:15 UTC, edward-prosser commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +These actions are triggered during a flow when a node needs to make a HTTP request via the client for the PSP's API.  In the case of `MockPaymentRail`, the actions are triggered when a flow needs to
Also unsure about `check-pointed`.

2021-01-05 14:02 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `actions`
```suggestion
* `actions`.
```

2021-01-05 14:03 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +### ModulrService
This is a notable part of the project structure.

2021-01-05 14:06 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `PaymentExecutionException` - This exception will be thrown if the currency specified is not `GBP`.
```suggestion
* `PaymentExecutionException` - This exception will be thrown if the currency specified is not one of the two accepted currencies: `GBP` or `EUR`.
```

2021-01-05 14:06 UTC, benpesterr3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +# Payments-core CorDapp (Pre-Alpha stage)
```suggestion
# Payments-core CorDapp (pre-alpha stage)
```

2021-01-05 14:21 UTC, benpesterr3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +This version of the Payments-core CorDapp contains all the flows and actions that are required to make payments between nodes, and between nodes and external parties. This means you can you can write
```suggestion
This version of the Payments-core CorDapp contains all the flows and actions that are required to make payments between nodes, and between nodes and external parties. This means you can you can write CorDapps that use these flows to facilitate payments, via a Payment Service Provider (PSP), on a Corda network.
```

2021-01-05 15:50 UTC, mattbradburyr3 submitted a review, later dismissed
Docs look good, caveats/ context looks good

2021-01-05 15:50 UTC, mattbradburyr3 commented on content/en/docs/apps/payments/payments-index.md
> +The Payments and ModulR payment rail pre-alpha CorDapps are early release features that allow you to create theoretical and experimental payment solutions in Corda - connecting to real Payment Servic
Capital 'R' sneaking in again

2021-01-08 19:19 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +
```suggestion

### GetAccountFlow

A flow used to retrieve an ISO20022 Return Account message with information concerning a specific account and it's balance.

#### Parameters

* `accountIdentifier` - An data class which contains the information required to create an ISO20022 message.
* `isoMessage` - An ISO formatted GetAccount message with all necessary query information.
* `paymentRail` - A string indicating with payment rail should be queried.

#### Return Type

`String` - This flow will return a ISO20022 formatted ReturnAccount message.
```

2021-01-08 19:32 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +`String` - This flow will request a list of enabled payment rails from the counterparty, filter the list to determine which payment rails are viable, and return the negotiated rail.
```suggestion
`Unit / Void` - None.

```

2021-01-08 19:41 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +`PaymentExecutionException` - This exception will be thrown if the specified `designatedPaymentRail`
```suggestion
```

2021-01-08 19:43 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +'''
Yup, this indicates a multi-line string in kotlin

2021-01-08 19:45 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +4. Build an idempotent action for initiating a payment and a non-idempotent action for querying a payment, all through the PSP.  This can be done by extending the abstract classes discussed in the Ex
```suggestion
4. Build an idempotent action for initiating a payment and a non-idempotent action for querying a payment, all through the PSP.  This can be done by extending the abstract classes discussed in the External Action Manager section below. These actions are triggered during a flow when a node needs to communicate with the client that you built in step 1.
```

2021-01-08 19:48 UTC, vganesan97 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `List<PaymentRecord>` - This flow will return a list of type `PaymentRecord`.
```suggestion
```

2021-01-11 07:30 UTC, ivanterziev-r3 requested changes
Hey Ben, looks good overall - a few comments and suggestions added.

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/_index.md
> +Within the documentation, you will find set-up guides, tips and operational instructions for a growing list of applications made for exploration and very early adoption.
```suggestion
Within the documentation, you will find set-up guides, tips, and operational instructions for a growing list of applications made for exploration and very early adoption.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +1. The Modulr payments CorDapp connects to the Modulr API.
There is a bit of inconsistency across the docs regarding the name of this. For example, we call the Payments-core a CorDapp here and there but not in all mentions, and we don't call the Modulr variant a CorDapp in its full naming, even in these first two bulleted lists it might be misleading as the first mention is "The Modulr payments CorDapp" and the second one is "The Modulr CorDapp" (unless the latter is a different CorDapp?). 
We all the Modulr app a solution above (and in the index), and a CorDapp here. Further below there is a mention of "Modulr payments rail". 

All these mentions should be made consistent across all pages.

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +5. The Modulr payments CorDapp polls the status of the payment through the Modulr API until Modulr returns a final state of PROCESSED or CANCELLED.
```suggestion
5. The Modulr payments CorDapp polls the status of the payment through the Modulr API until Modulr returns a final state of either `PROCESSED` or `CANCELLED`.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Use this documentation to explore the `modulr-rail` module. You should also be familiar with the Payments-core CorDapp before using this rail.
add link to the -core page

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +### Client Module
```suggestion
### Client module
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The `com.r3.payments.modulr.client` package contains the `ModulrClient` class, a wrapper class which acts as a proxy to the Modulr API.  The `client` obtains data from the Modulr API via HTTP calls t
```suggestion
The `com.r3.payments.modulr.client` package contains the `ModulrClient` class, a wrapper class which acts as a proxy to the Modulr API. The `client` obtains data from the Modulr API via HTTP calls to REST endpoints.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +`ModulrService`, an implementation of `PaymentRailServiceInterface` from [Payments-core CorDapp](payments-core-cordapp), provides access to a `ModulrClient` that will be shared across flows -- execut
```suggestion
`ModulrService`, an implementation of `PaymentRailServiceInterface` from [Payments-core CorDapp](payments-core-cordapp), provides access to a `ModulrClient` that will be shared across flows - executing actions that require interaction with the Modulr API. This abstraction provides a safe and resource-efficient way for a Corda node to communicate with the Modulr API.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Learn more about `Actions`/`IdempotentAction` and `external-action-manager` here: (link to external action manager section in `payments-core CorDapp`)
Seems to be a missing link here as per the text in brackets?

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The actions package contains idempotent and non-idempotent actions to communicate with the Modulr API using the `ModulrClient`.  The following is a list of all the classes that contain actions used i
```suggestion
The actions package contains idempotent and non-idempotent actions to communicate with the Modulr API using the `ModulrClient`. The following is a list of all the classes that contain actions used in this CorDapp followed by the abstract class which is extended `external-action-manager`.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The actions package contains idempotent and non-idempotent actions to communicate with the Modulr API using the `ModulrClient`.  The following is a list of all the classes that contain actions used i
Please check the suggestions above - the name of the class and whether this is what you meant to write

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The flows package contains flows that allow a node to send a payment to another node, an external destination (not a corda node), and a flow to retrieve the status of a payment --  all using the Modu
```suggestion
The flows package contains flows that allow a node to send a payment to another node, an external destination (not a Corda node), and a flow to retrieve the status of a payment - all using the Modulr API.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Respective flows trigger an action which in turn communicate with the Modulr API through the `ModulrClient`.  The following is a list of flows used by modulr-rails-cordapp.
Update "modulr-rails-cordapp" to the correct term

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +These are not to be used directly by the developer, they are only accessible through the payments-core CorDapp.
```suggestion
These are not to be used directly by the developer, they are only accessible through the Payments-core CorDapp.  
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +These are not to be used directly by the developer, they are only accessible through the payments-core CorDapp.
Also perhaps add a link here

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Makes a payment using the Modulr api and client to a destination not represented by a corda node.This flow executes an `InitiateModulrPayment` after constructing a `PaymentInitiationPayload` from a r
```suggestion
Makes a payment using the Modulr API and client to a destination not represented by a Corda node. This flow executes an `InitiateModulrPayment` after constructing a `PaymentInitiationPayload` from a received `isoMessage`. It will then continue to poll for the results of the initiated payment and return the payment entity once it has been processed.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `isoMessage` - A XML message formatted in ISO20022.
My personal preference is to use : instead of - in these structures but I guess this is something we need to agree on in the team for the style guide recommendation.

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +This flow initiates a payment using the Modulr payment rail.  It will construct and execute an `InitiateModulrPayment` action using the provided `Destination` to create a modulr specific `PaymentInit
A note on term consistency - is it "payment rail" or "payments rail"? Both are used in these pages.

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +This flow initiates a payment using the Modulr payment rail.  It will construct and execute an `InitiateModulrPayment` action using the provided `Destination` to create a modulr specific `PaymentInit
```suggestion
This flow initiates a payment using the Modulr payment rail.  It will construct and execute an `InitiateModulrPayment` action using the provided `Destination` to create a Modulr-specific `PaymentInitiationPayload` as required input.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `paymentId` - The ID of the payment that has been submitted for processing by the Modulr payment rail
```suggestion
* `paymentId` - The ID of the payment that has been submitted for processing by the Modulr payments rail.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +You must log in as a Party to make a payment or get the status of a payment.  After logging in, you must make a payment before using GetPayment. The payment will take 1.9 minutes, almost exactly. The
```suggestion
You must log in as a Party to make a payment or get the status of a payment.  After logging in, you must make a payment before using `GetPayment`. The payment will take 1.9 minutes, almost exactly. The only supported currency is EUR.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +## Creating and Installing the CorDapp Jar
```suggestion
## Creating and installing the CorDapp `.jar` file
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Once your dependencies are set correctly, you can build your CorDapp JAR(s) using the Gradle jar task
```suggestion
Once your dependencies are set correctly, you can build your CorDapp `.jar` file(s) using the Gradle `jar` task
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Each of the project’s modules will be compiled into its own CorDapp JAR. You can find these CorDapp JARs in the build/libs folders of each of the project’s modules.
```suggestion
Each of the project’s modules will be compiled into its own CorDapp `.jar` file. You can find these CorDapp `.jar` files in the `build/libs` folders of each of the project’s modules.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The hash of the generated CorDapp JAR is not deterministic, as it depends on variables such as the timestamp at creation. Nodes running the same CorDapp must therefore ensure they are using the exact
```suggestion
The hash of the generated CorDapp `.jar` file is not deterministic, as it depends on variables such as the timestamp at creation. Nodes running the same CorDapp must therefore ensure they are using the exact same CorDapp `.jar` file, and not different versions of the `.jar` file created from identical sources.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The filename of the JAR must include a unique identifier to deduplicate it from other releases of the same CorDapp. This is typically done by appending the version string to the CorDapp’s name. This
```suggestion
The file name of the `.jar` file must include a unique identifier to deduplicate it from other releases of the same CorDapp. This is typically done by appending the version string to the CorDapp’s name. This unique identifier should not change once the `.jar` file has been deployed on a node. If it does change, make sure no one is relying on `FlowContext.appName` in their flows (see Versioning).
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +The filename of the JAR must include a unique identifier to deduplicate it from other releases of the same CorDapp. This is typically done by appending the version string to the CorDapp’s name. This
Add a link to Versioning (in the OS doc set)

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +At start-up, nodes will load any CorDapps present in their cordapps folder. In order to install a CorDapp on a node, the CorDapp JAR must be added to the <node_dir>/cordapps/ folder (where node_dir i
```suggestion
At start-up, nodes will load any CorDapps present in their `cordapps` folder. In order to install a CorDapp on a node, the CorDapp `.jar` file must be added to the `<node_dir>/cordapps/` folder (where `node_dir` is the folder in which the node’s `.jar` file and configuration files are stored) and the node must be restarted.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/payments-index.md
> +Checkout the [Modulr payment rail solution](modulr-payment-rail), designed to trial live payments through the Modulr PSP.
See my other comments about the naming consistency

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/apps/payments/payments-index.md
> +Checkout the [Modulr payment rail solution](modulr-payment-rail), designed to trial live payments through the Modulr PSP.
Also add link to Modulr site

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.7/release-notes.md
> +#### Corda Payments Alpha
Two things:
1. This section should be appended as a top-level section (same level as `## Corda 4.7`) on top of the page. This release is NOT part of the Corda 4.7 release, so needs to be separate from it. I think this is what we agreed before. 
2. Please add the same section to the CE 4.7 release notes - append on top of page.
3. 
For both entries you could use a combined `## Featured Apps - Corda Payments Alpha` or something similar to indicate that this is an app outside of the platform release.

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.7/release-notes.md
> +[Corda Payments Alpha](../../apps/payments/payments-index.md) is a first glimpse at a new app that allows you to create your own payment solution in Corda.
```suggestion
[Corda Payments Alpha](../../apps/payments/payments-index.md) is a first glimpse at a new set of Apps that allows you to create your own payment solution in Corda.
```

2021-01-11 07:30 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.7/release-notes.md
> +- Trial a live payments solution using Modulr as the Payment Service Provider.
Add a link to the official Modulr site

2021-01-11 08:21 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Use this documentation to explore the `modulr-rail` module. You should also be familiar with the Payments-core CorDapp before using this rail.
```suggestion
Use this documentation to explore the `modulr-rail` module. You should also be familiar with the [Payments-core CorDapp](payments-core-cordapp) before using this rail.
```

2021-01-11 08:23 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Learn more about `Actions`/`IdempotentAction` and `external-action-manager` here: (link to external action manager section in `payments-core CorDapp`)
```suggestion
Learn more about `Actions`/`IdempotentAction` and `external-action-manager` in the [Payments-core documentation](payments-core-cordapp). 
```

2021-01-11 08:30 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +This payment rail uses the Payments-core CorDapp to make payments and retrieve payment data.
```suggestion
This payment rail uses the [Payments-core CorDapp](payments-core-cordapp) to make payments and retrieve payment data.
```

2021-01-11 08:31 UTC, benpesterr3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +4. The Modulr payments CorDapp sends an HTTP request containing the specified payment initiation payload to the Modulr API. Modulr provides different environment URLs which we specify in the node's c
```suggestion
4. The Modulr Payment Rail CorDapp sends an HTTP request containing the specified payment initiation payload to the Modulr API. Modulr provides different environment URLs which we specify in the node's configuration.
```

2021-01-11 09:29 UTC, ivanterziev-r3 submitted a review, later dismissed
LGTM

2021-01-11 10:14 UTC, ivanterziev-r3 commented on themes/hugo-r3-theme/layouts/index.html
> +      "docs/apps/payments-index.html">
```suggestion
      "docs/apps/payments/payments-index.html">
```

2021-01-11 10:36 UTC, taylorharvey-r3 reviewed
Made some small suggestions and comments throughout. Overall it looks great! Menus rendered correctly too. 
One additional question on menu structure - in the main menu, Apps is between Corda OS 4.7 and CENM 1.5. Is this correct?

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +2. The POJO representing the ISO message under goes syntactic, semantic and scope validations.
```suggestion
2. The POJO representing the ISO message under goes syntactic, semantic, and scope validations.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `isoMessage` - A XML message formatted in ISO20022.
```suggestion
* `isoMessage` - An XML message formatted in ISO20022.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +A flow used to retrieve an ISO20022 Return Account message with information concerning a specific account and it's balance.
```suggestion
A flow used to retrieve an ISO20022 ReturnAccount message with information concerning a specific account and its balance.
```
ReturnAccount and GetAccount do not have a space below. Should these have back ticks?

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `accountIdentifier` - An data class which contains the information required to create an ISO20022 message.
```suggestion
* `accountIdentifier` - A data class which contains the information required to create an ISO20022 message.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +`String` - This flow will return a ISO20022 formatted ReturnAccount message.
```suggestion
`String` - This flow will return an ISO20022 formatted ReturnAccount message.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +A flow that retrieves a ISO20022 message containing information about a payment with the specified ID.
```suggestion
A flow that retrieves an ISO20022 message containing information about a payment with the specified ID.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +`String` - This flow will return a ISO20022 formatted message with information about the specified payment.
```suggestion
`String` - This flow will return an ISO20022 formatted message with information about the specified payment.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `counterParty` - The legal identity of the counter-party with whom we should be negotiating payment details.
```suggestion
* `counterParty` - The legal identity of the counter-party with whom you should be negotiating payment details.
```
We or you? I think this is the first time I can recall seeing "we" in the text but may be wrong.

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +`session` - The flow session provided by Corda, which we will use to respond to the initiating party..
```suggestion
`session` - The flow session provided by Corda, which we will use to respond to the initiating party.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +This flows sends a completed payment id to the counter party.
```suggestion
This flows sends a completed payment ID to the counter party.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* **Outgoing** - where an ISO message is sent from `payments-core`
```suggestion
* **Outgoing** - where an ISO message is sent from `payments-core`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +The ISO 20022 message formats are described in a set of .xsd files published by the ISO 20022 Registration Authority (RA).
```suggestion
The ISO 20022 message formats are described in a set of `.xsd` files published by the ISO 20022 Registration Authority (RA).
```
I think this was mentioned elsewhere above. Can you provide a link to this?

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +As part of the marshalling/ unmarshalling processes the XMLs are checked to make sure they are syntactically correct per the xsds. This ensures that all XML elements included are valid components of
```suggestion
As part of the marshalling/ unmarshalling processes the XMLs are checked to make sure they are syntactically correct per the xsds. This ensures that all XML elements included are valid components of the overarching message set. It also enforces rules about order, required fields, duplicated elements, and other more nuanced payment details.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +  * For some elements in the XML, the xsd does not define the allowed values, instead this is delegated to a separately defined set of allowed codes published by swift.
```suggestion
  * For some elements in the XML, the xsd does not define the allowed values, instead this is delegated to a separately defined set of allowed codes published by Swift.
```
Swift? SWIFT?

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* SemanticValidator -> defines validateSemantics() function
```suggestion
* `SemanticValidator` -> defines `validateSemantics()` function.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* CodeSetValidator -> defines validateCodeSets() function
```suggestion
* `CodeSetValidator` -> defines `validateCodeSets()` function.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* ScopeValidator -> defines validateScope() function
```suggestion
* `ScopeValidator` -> defines `validateScope()` function.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* SemanticRule -> defines validateSemanticRule() function
```suggestion
* `SemanticRule` -> defines `validateSemanticRule()` function
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* ScopeRestriction -> defines validateScopeRestrition() function
```suggestion
* `ScopeRestriction` -> defines `validateScopeRestrition()` function
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* CodeSetCheck -> defines validateCodeSet() function
```suggestion
* `CodeSetCheck` -> defines `validateCodeSet()` function
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +The `mock-payment-rail` module contains two sub-packages: `actions` and `flows`
```suggestion
The `mock-payment-rail` module contains two sub-packages: `actions` and `flows`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `clientDeduplicationId` - An ID submitted by the invoking client for the purposes of deduplication
```suggestion
* `clientDeduplicationId` - An ID submitted by the invoking client for the purposes of deduplication.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `session` - The flow session provided by Corda which we will use to respond to the initiating party.
```suggestion
* `session` - The flow session provided by Corda which you will use to respond to the initiating party.
```
We or you again. Up to you!

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +* `destination` - UniqueIdentifier of beneficiary
```suggestion
* `destination` - UniqueIdentifier of beneficiary.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +Once your dependencies are set correctly, you can build your CorDapp JAR(s) using the Gradle jar task
```suggestion
Once your dependencies are set correctly, you can build your CorDapp JAR(s) using the Gradle jar task:
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +The filename of the JAR must include a unique identifier to deduplicate it from other releases of the same CorDapp. This is typically done by appending the version string to the CorDapp’s name. This
```suggestion
The filename of the JAR must include a unique identifier to deduplicate it from other releases of the same CorDapp. This is typically done by appending the version string to the CorDapp’s name. This unique identifier should not change once the JAR has been deployed on a node. If it does, make sure no one is relying on `FlowContext.appName` in their flows (see Versioning).
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +At start-up, nodes will load any CorDapps present in their cordapps folder. In order to install a CorDapp on a node, the CorDapp JAR must be added to the <node_dir>/cordapps/ folder (where node_dir i
```suggestion
At start-up, nodes will load any CorDapps present in their cordapps folder. In order to install a CorDapp on a node, the CorDapp JAR must be added to the `<node_dir>/cordapps/` folder (where `node_dir` is the folder in which the node’s JAR and configuration files are stored) and the node restarted.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +2. Run the following command: `./gradlew clean deployNodes`
```suggestion
2. Run the following command: `./gradlew clean deployNodes`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/payments-core-cordapp.md
> +3. After the project has been built succesfully, run the following command to run the nodes: `build/nodes/runnodes`
```suggestion
3. After the project has been built succesfully, run the following command to run the nodes: `build/nodes/runnodes`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `GetModulrAccounts` extends `Action`
```suggestion
- `GetModulrAccounts` extends `Action`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `CreateModulrAccountByCustomer` extends `IdempotentAction`
```suggestion
- `CreateModulrAccountByCustomer` extends `IdempotentAction`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `GetModulrCustomers` extends `Action`
```suggestion
- `GetModulrCustomers` extends `Action`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `InitiateModulrPayment` extends `IdempotentAction`
```suggestion
- `InitiateModulrPayment` extends `IdempotentAction`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `GetModulrPaymentByDeduplicationId` extends `Action`
```suggestion
- `GetModulrPaymentByDeduplicationId` extends `Action`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +- `GetModulrPaymentByID` extends `Action`
```suggestion
- `GetModulrPaymentByID` extends `Action`.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `destination` - Information surrounds the destination (beneficiary) of the payment.
```suggestion
* `destination` - Information surrounding the destination (beneficiary) of the payment.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `isoMessage` - A XML message formatted in ISO20022.
```suggestion
* `isoMessage` - An XML message formatted in ISO20022.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* `String` - This flow will return a XML `String` representing the balance of the specified account.
```suggestion
* `String` - This flow will return an XML `String` representing the balance of the specified account.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +* Get the status of a payment status.
```suggestion
* Get the status of a payment.
```

2021-01-11 10:36 UTC, taylorharvey-r3 commented on content/en/docs/apps/payments/modulr-payment-rail.md
> +Once your dependencies are set correctly, you can build your CorDapp `.jar` file(s) using the Gradle `jar` task
```suggestion
Once your dependencies are set correctly, you can build your CorDapp `.jar` file(s) using the Gradle `jar` task:
```

2021-01-11 11:37 UTC, ivanterziev-r3 approved these changes
LGTM

2021-01-11 12:28 UTC, merged