EG-4699: Added some missing steps, examples, updated version numbers listed.
corda/corda-docs pull request #395
Opened 2021-02-02 14:50 UTC by taylorharvey-r3

@edward-prosser , @ivanterziev-r3 Could you take a look at this PR? Updating the Build the docs page in our OS docs to reflect some missing steps and examples. It would be great if you could look closely at added examples and commands to be sure they are correct and clear.

2021-02-02 14:57 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +2. Download [Hugo](https://github.com/gohugoio/hugo/releases). Use the latest, extended version, otherwise at least v0.65.
Perhaps use the format in this readme (the intro para but whatever else you think would be helpful):

https://github.com/corda/engineering-kb#install-hugo

2021-02-02 15:58 UTC, ivanterziev-r3 requested changes
A few things need changing, didn't have time for a very detailed review so can look more thoroughly in the next iteration

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +5. Clone your fork locally and, in command-line, navigate (`cd`) to root of the fork repo.
```suggestion
5. Clone your fork locally.
6. Open a a console / command prompt window and navigate (`cd`) to the root directory of the fork repo.
```

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
>  7. Open the local docs site build on [http://localhost:1313](http://localhost:1313) (or whatever it says in the console) in your browser.
```suggestion
7. Open the local docs site built on [http://localhost:1313](http://localhost:1313) in your browser.
```

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
>  upstream	git://github.com/corda/corda-docs.git (push)
I think this may be an error (also in the older version of that instruction where I worked from back in the day when updating this page of 4.4+) - the upstream entries should also be in https:// format. Also, my name should not be anywhere in the public docs apparently... another mistake:)) 
Can you replace with:

`origin	https://github.com/my-github-username/corda-docs.git (fetch)  #  YOUR FORK`
`origin	https://github.com/my-github-username/corda-docs.git (push)`
`upstream	https://github.com/corda/corda-docs.git (fetch)  #  THE ORIGINAL REPO`
`upstream	https://github.com/corda/corda-docs.git (push)`

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +Alternatively, if you are accessing GitHub without an `ssh` key:
This is again for https and not ssh access? One of the two should become ssh...

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +To remove the `upstream` repo:
```suggestion
If you need to remove the `upstream` repo for any reason:
```

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +To remove the `upstream` repo:
NB This should be amended in our instructions in the KB as well as this not a normal use case and it may be misleading if we leave if this way

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
>  `$ git fetch upstream`
Please can you remove the $ prefixes from all commands, not sure why they are there in the first place...

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.5/building-the-docs.md
>  Steps:
same changes as in the 4.4 doc

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/building-the-docs.md
same changes as in the 4.4 doc

2021-02-02 15:58 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.7/building-the-docs.md
same changes as in the 4.4 doc

2021-02-02 19:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.4/building-the-docs.md
> +Alternatively, if you are accessing GitHub without an `ssh` key:
Good spot! Fixed in upcoming commit.

2021-02-03 09:30 UTC, ivanterziev-r3 approved these changes
LGTM

2021-02-03 09:44 UTC, merged