DOC-1742: cloning auth service and gateway service files
corda/corda-docs pull request #410
Opened 2021-02-24 15:13 UTC by AMcFarlandCampbellR3

2021-03-11 11:12 UTC, farm requested changes

2021-03-11 11:12 UTC, farm commented on content/en/docs/cenm/1.5/user-admin.md
>  ## Access the CENM User Admin tool
This should no longer be referred to as the CENM User admin tool, since we're covering other applications as well - just use "User Administration tool"

2021-03-11 11:12 UTC, farm commented on content/en/docs/cenm/1.5/_index.md
> +* [Auth Service](../../corda-enterprise/4.7/node/auth-service.md) The user authentication and authorization service for CENM. Stores and controls secure user-access to network services.
This may cause confusion if we explicitly say it's for CENM specifically?

2021-03-11 11:12 UTC, farm commented on content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes-auth.md
> +This Helm chart is to configure, deploy, and run the [CENM Auth Service](../../node/auth-service.md) on Kubernetes.
CENM Auth Service - old name

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/_index.md
> +* [Gateway service](../../corda-enterprise/4.7/node/gateway-service.md)
```suggestion
* [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md)
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/aws-deployment-postgressql.md
> +* [Auth service](../../corda-enterprise/4.7/node/auth-service).
```suggestion
* [Auth Service](../../corda-enterprise/4.7/node/auth-service).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/aws-deployment-postgressql.md
> +* [Gateway service](../../corda-enterprise/4.7/node/gateway-service).
```suggestion
* [Gateway Service](../../corda-enterprise/4.7/node/gateway-service).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/aws-deployment-postgressql.md
>  * [Identity manager](identity-manager).
```suggestion
* [Identity Manager](identity-manager).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/aws-deployment-postgressql.md
>  * [Signer service](signing-service).
```suggestion
* [Signer Service](signing-service).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/cenm-console.md
> +- [Gateway service](../../corda-enterprise/4.7/node/gateway-service.md) is installed and running.
```suggestion
- [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md) is installed and running.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/cenm-console.md
> +The CENM management console is accessed via the [Gateway service](../../corda-enterprise/4.7/node/gateway-service.md). Once you have added the plugin binaries to the correct directory on the machine
```suggestion
The CENM management console is accessed via the [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md). Once you have added the plugin binaries to the correct directory on the machine that hosts your Gateway Service, you can access the web service from any browser.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/release-notes.md
> +CENM 1.5 introduces support for Azure Active Directory (AAD) as a Single sign-on (SSO) for the CENM [Auth Service](../../corda-enterprise/4.7/node/auth-service.md), which supports full Role-Based Acc
```suggestion
CENM 1.5 introduces support for Azure Active Directory (AAD) as a single sign-on (SSO) for the CENM [Auth Service](../../corda-enterprise/4.7/node/auth-service.md), which supports full Role-Based Access Control (RBAC) and provides a web-based management interface for system administrators to create and manage user groups and entitlements. As a result, you can now operate a SSO set-up between Corda services and Azure AD, with a [simple configuration](../../corda-enterprise/4.7/node/azure-ad-sso/) to both your Azure AD and Corda Auth services.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/release-notes.md
> +* We have fixed an issue where [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md) (previously called FARM Service in CENM 1.2) logs were not available in the `logs-farm` container.
```suggestion
* We have fixed an issue where [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md) (previously called FARM Service in CENM 1.3) logs were not available in the `logs-farm` container.
```
See the _Other changes_ section, bullet point no 3.

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/user-admin.md
> +You access the User Admin tool from the location of your [Gateway service](../../corda-enterprise/4.7/node/gateway-service#manage-your-configuration) instance. Enter the full address of your Gateway
```suggestion
You access the User Admin tool from the location of your [Gateway Service](../../corda-enterprise/4.7/node/gateway-service#manage-your-configuration) instance. Enter the full address of your Gateway Service, including the port number, followed by `/admin` into a web browser.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
>  # Auth service
```suggestion
# Auth Service
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +The Auth service is the user authentication and authorization service for managing Corda Nodes and networks (CENM). It stores and controls secure user-access to network services, such as:
```suggestion
The Auth Service is the user authentication and authorization service for managing Corda Nodes and networks (CENM). It stores and controls secure user-access to network services, such as:
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Identity manager
```suggestion
* Identity Manager
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Zone service
```suggestion
* Zone Service
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Signing service
```suggestion
* Signing Service
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Network map (and associated network configurations and node info)
```suggestion
* Network Map (and associated network configurations and node info)
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +Whenever you use the [CENM User admin tool](../../../cenm/1.5/user-admin) to create new users, groups or roles, the Auth service is updated to authenticate those users and their permissions. When usi
```suggestion
Whenever you use the [CENM User admin tool](../../../cenm/1.5/user-admin) to create new users, groups or roles, the Auth Service is updated to authenticate those users and their permissions. When using the remote management tools such as the [CENM Command Line Interface](../../../cenm/1.5/cenm-cli-tool) or the web GUIs hosted on the Gateway Service, the Auth Service verifies your identity and security clearance as needed.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +You do not need to interact directly with the Auth Service once it has been installed and configured. To protect the integrity of this secure service, there is no direct API contact with the Auth Ser
```suggestion
You do not need to interact directly with the Auth Service once it has been installed and configured. To protect the integrity of this secure service, there is no direct API contact with the Auth Service: all front-end communications go via the Gateway Service.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +Auth service can also be configured to use [Azure AD SSO](azure-ad-sso).
```suggestion
Auth Service can also be configured to use [Azure AD SSO](azure-ad-sso).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
>  2. Generate a `jwt` signing key (RSA keypair) in a jks file with the following command line command:
```suggestion
2. Generate a JWT signing key (RSA keypair) in a `.jks` file with the following command-line command:
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +1. [Database configuration](../../../cenm/1.5/database-set-up). Add the name, address and login credentials for the SQL database that supports the Auth service.
```suggestion
1. [Database configuration](../../../cenm/1.5/database-set-up). Add the name, address and login credentials for the SQL database that supports the Auth Service.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
>  2. JSON Web Key configuration. Set the username, password, and location of the RSA keypair store for signing. The location must be the absolute path.
```suggestion
2. JSON Web Key configuration. Set the user name, password, and location of the RSA keypair store for signing. The location must be the absolute path.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +Auth service needs to be set up with baseline permission data for each application.
```suggestion
Auth Service needs to be set up with baseline permission data for each application.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/gateway-service.md
> +## Install the gateway Gateway service
```suggestion
## Install the Gateway Service
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/gateway-service.md
>  1. Specify the endpoint where the Auth service is exposed - this must match the IP or host name of the machine/VM/container and the port that is configured in the Auth Service config file.
```suggestion
1. Specify the endpoint where the Auth Service is exposed - this must match the IP or host name of the machine/VM/container and the port that is configured in the Auth Service config file.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/gateway-service.md
> +2. Specify the SSL configuration for connecting to the Auth service. You can do this using the [PKI tool](../../../cenm/1.5/pki-tool).
```suggestion
2. Specify the SSL configuration for connecting to the Auth Service. You can do this using the [PKI tool](../../../cenm/1.5/pki-tool).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/gateway-service.md
> +[Auth service](auth-service) needs to be set up with baseline permission data for each application.
```suggestion
[Auth Service](auth-service) needs to be set up with baseline permission data for each application.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/management-console/_index.md
> +The node management console allows you to see information about a node and perform some operations on it. It runs as a plug-in for the [Gateway service](../gateway-service.md).
```suggestion
The node management console allows you to see information about a node and perform some operations on it. It runs as a plug-in for the [Gateway Service](../gateway-service.md).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/management-console/_index.md
> +1. Put `node-management-plugin-<release>.jar` into the `plugins` directory in the Gateway service
```suggestion
1. Put `node-management-plugin-<release>.jar` into the `plugins` directory in the Gateway Service
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/management-console/_index.md
> +2. Put `auth-baseline-node-management-<release>.jar` into the `plugins` directory in the Auth service.
```suggestion
2. Put `auth-baseline-node-management-<release>.jar` into the `plugins` directory in the Auth Service.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> +The flow management console allows you to see the state of the flows running on a node and perform some operations on them. It runs as part of the [Gateway service](gateway-service.md).
```suggestion
The flow management console allows you to see the state of the flows running on a node and perform some operations on them. It runs as part of the [Gateway Service](gateway-service.md).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> +1. Put `flow-management-plugin-<release>.jar` into the `plugins` directory in the Gateway service
```suggestion
1. Put `flow-management-plugin-<release>.jar` into the `plugins` directory in the Gateway Service.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> +2. Put `auth-baseline-flow-management-<release>.jar` into the `plugins` directory in the Auth service.
```suggestion
2. Put `auth-baseline-flow-management-<release>.jar` into the `plugins` directory in the Auth Service.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> + * Clicking on a pie chart _section_ redirects to the query flows tab with a filter applied for that flow state.
```suggestion
 * Clicking on a pie chart _section_ redirects you to the query flows tab with a filter applied for that flow state.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
>  * A bar chart which lists flows by suspension duration, starting with the longest duration on the left. Clicking on a flow redirects the user to the query flows page filtered on that specific flow. T
```suggestion
* A bar chart which lists flows by suspension duration, starting with the longest duration on the left. Clicking on a flow redirects you to the query flows page filtered on that specific flow. This chart has options for choosing how many flows to display and to filter out flows that have not been suspended for a specified amount of time (for example, only display flows that have been suspended for at least 20 minutes).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes.md
> +The [Gateway Service](../../node/gateway-service.md) is a gateway between the [Auth Service](../../node/auth-service.md) and front end services in CENM. It allows you to perform all network operation
```suggestion
The [Gateway Service](../../node/gateway-service.md) is a gateway between the [Auth Service](../../node/auth-service.md) and front-end services in CENM. It allows you to perform all network operations on the [Identity Manager Service](../../../../cenm/1.5/identity-manager.md), the [Network Map Service](../../../../cenm/1.5/network-map.md), and the [Signing Service](../../../../cenm/1.5/signing-service.md).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
> +They both run as part of the [Gateway service](node/gateway-service.md).
```suggestion
They both run as part of the [Gateway Service](node/gateway-service.md).
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/release-notes-enterprise.md
> +* **Single sign-on for Azure AD.** You can now operate a single sign on (SSO) set-up between Corda services and Azure AD, with a [simple configuration](node/azure-ad-sso/) to both your Azure AD and C
```suggestion
* **Single sign-on for Azure AD.** You can now operate a single sign-on (SSO) set-up between Corda services and Azure AD, with a [simple configuration](node/azure-ad-sso/) to both your Azure AD and Corda Auth services.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/cenm/1.5/upgrade-notes.md
>  * Does not contain the username.
```suggestion
* Does not contain the user name.
```

2021-03-11 11:34 UTC, AnnaK-R3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
>  2. JSON Web Key configuration. Set the username, password, and location of the RSA keypair store for signing. The location must be the absolute path.
```suggestion
2. JSON Web Key configuration. Set the user name, password, and location of the RSA keypair store for signing. The location must be the absolute path.
```

2021-03-11 12:24 UTC, conor-r3 commented on content/en/docs/cenm/1.5/deployment-kubernetes-auth.md
> +This Helm chart is to configure, deploy, and run the [CENM Auth Service](../../corda-enterprise/4.7/node/auth-service.md) on Kubernetes.
Is there a reason why this is referred to as the CENM Auth Service instead of just the Auth Service?

2021-03-11 12:34 UTC, conor-r3 commented on content/en/docs/cenm/1.5/deployment-kubernetes.md
>  To star CENM CLI Tool run Docker command starting Docker container with the tool:
I think this sentence would be clearer with articles added.
```suggestion
To start the CENM CLI Tool, run Docker command starting a Docker container with the tool:
```

2021-03-11 12:41 UTC, conor-r3 commented on content/en/docs/cenm/1.5/upgrade-notes.md
>  * Does not contain the username.
I don't want to be bike-shedding, but I think `username` is correct.
[Reference](https://english.stackexchange.com/a/43470/58688)

2021-03-11 12:47 UTC, szymonsztuka commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Identity manager
Shouldn't be all CENM services grouped together - just to distinguish it from Nodes?

2021-03-11 12:52 UTC, conor-r3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> + * Clicking on the _name_ of a section in the legend removes matching flow states from the pie chart.
In version 1.0.1 of the plugin (which has not been released yet), we move to a different charting library and this bullet point will no longer be true. I guess we can make that update in the future, but I thought I'd call it out here.

2021-03-11 12:55 UTC, conor-r3 commented on content/en/docs/cenm/1.5/deployment-kubernetes-auth.md
> +This Helm chart is to configure, deploy, and run the [CENM Auth Service](../../corda-enterprise/4.7/node/auth-service.md) on Kubernetes.
```suggestion
This Helm chart is to configure, deploy, and run the [Auth Service](../../corda-enterprise/4.7/node/auth-service.md) on Kubernetes.
```

2021-03-11 12:56 UTC, conor-r3 commented on content/en/docs/cenm/1.5/deployment-kubernetes-gateway.md
> +This Helm chart is to configure, deploy, and run the [CENM Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md) on Kubernetes.
```suggestion
This Helm chart is to configure, deploy, and run the [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md) on Kubernetes.
```

2021-03-12 15:57 UTC, AMcFarlandCampbellR3 commented on content/en/docs/corda-enterprise/4.7/node/node-flow-management-console.md
> + * Clicking on the _name_ of a section in the legend removes matching flow states from the pie chart.
I think we can update that when the update happens.

2021-03-13 13:53 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/_index.md
>  title: Azure AD SSO
Please also review other CENM pages that refer to the azure-sso page - there may be some links in index/landing pages and so on. Same goes for the gateway and auth service page moves - there are likely to be a lot of references from across the CENM docs to these.

2021-03-13 13:56 UTC, ivanterziev-r3 commented on content/en/docs/cenm/1.5/release-notes.md
> +* We have renamed the FARM Service, introduced in CENM 1.3, to [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md). As a result, if you are [upgrading](upgrade-notes.md) from CENM 1
I thought the change was only in CENM 1.5 / CE 4.7? If that's the case, then please revert all changes in links to CENM release notes content prior to 1.5 since the CENM 1.4 pages are still under CENM and not CE?

2021-03-24 13:38 UTC, AMcFarlandCampbellR3 commented on content/en/docs/cenm/1.5/user-admin.md
>  ## Access the CENM User Admin tool
Updated

2021-03-24 13:39 UTC, AMcFarlandCampbellR3 commented on content/en/docs/cenm/1.5/_index.md
> +* [Auth Service](../../corda-enterprise/4.7/node/auth-service.md) The user authentication and authorization service for CENM. Stores and controls secure user-access to network services.
Updated

2021-03-24 13:40 UTC, AMcFarlandCampbellR3 commented on content/en/docs/corda-enterprise/4.7/operations/deployment/deployment-kubernetes-auth.md
> +This Helm chart is to configure, deploy, and run the [CENM Auth Service](../../node/auth-service.md) on Kubernetes.
Updated

2021-03-24 13:50 UTC, AMcFarlandCampbellR3 commented on content/en/docs/corda-enterprise/4.7/node/gateway-service.md
> +The Gateway Service acts as common entry point for remote management of Corda Nodes as well as networks using CENM - either using the available command-line tools or via the web applications hosted b
I see what you mean, but i think the text is OK as it is.

2021-03-24 13:53 UTC, AMcFarlandCampbellR3 commented on content/en/docs/corda-enterprise/4.7/node/azure-ad-sso/_index.md
>  title: Azure AD SSO
There are only two links to this page in the CENM 1.5 documentation, and they have been updated. I have also run a link checker to check there are no broken links caused by the restructuring in this PR.

2021-03-24 14:01 UTC, AMcFarlandCampbellR3 commented on content/en/docs/cenm/1.5/release-notes.md
> +* We have renamed the FARM Service, introduced in CENM 1.3, to [Gateway Service](../../corda-enterprise/4.7/node/gateway-service.md). As a result, if you are [upgrading](upgrade-notes.md) from CENM 1
This is sightly complicated. The change is only to CENM 1.5 and CE 4.7, and the section you refer to is in the CENM 1.4 section, but _before_ this change, the CENM 1.4 section of the CENM 1.5 release notes pointed to the CENM 1.5 page on the Gateway Service.

We have two options.
* Leave it as it is; the updated CENM 1.5 release notes will not be any more incorrect than they were before the change. (Or, putting it another way, this change does not introduce any new errors.)
* Update this link to point to the 'correct' CENM 1.4 documentation, but that would mean updating all the links in the release notes to point to the correct version of the files. There are a lot of links in the 1.4 and 1.3 sections of the release notes that point to the 1.5 docs.

If we go for the second option, we should probably do that as part of a new ticket.

2021-04-01 14:10 UTC, jmacmahonr3 submitted a review, later dismissed
LGTM

2021-04-01 14:40 UTC, conor-r3 submitted a review, later dismissed

2021-04-01 15:04 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.5/release-notes.md
> +CENM 1.5 introduces support for Azure Active Directory (AAD) as a single sign-on (SSO) for the CENM [Auth Service](../../corda-enterprise/4.7/node/auth-service.md), which supports full Role-Based Acc
```suggestion
CENM 1.5 introduces support for Azure Active Directory (AAD) as a single sign-on (SSO) for the CENM [Auth Service](../../corda-enterprise/4.7/node/auth-service.md), which supports full Role-Based Access Control (RBAC) and provides a web-based management interface for system administrators to create and manage user groups and entitlements. As a result, you can now operate an SSO set-up between Corda services and Azure AD, with a [simple configuration](../../corda-enterprise/4.7/node/azure-ad-sso/) to both your Azure AD and Corda Auth services.
```

2021-04-01 15:06 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +The Auth Service is the user authentication and authorization service for managing Corda Nodes and networks (CENM). It stores and controls secure user-access to network services, such as:
```suggestion
The Auth Service is the user authentication and authorisation service for managing Corda Nodes and networks (CENM). It stores and controls secure user-access to network services, such as:
```

2021-04-01 15:09 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.7/node/auth-service.md
> +* Nodes
```suggestion
* Nodes.
```
Do we use full stops in unordered lists? I think that's what the style guide says (though I do recall a rather heated debate about it shortly after I joined).

2021-04-01 15:54 UTC, szymonsztuka submitted a review, later dismissed

2021-04-01 16:04 UTC, taylorharvey-r3 reviewed
I've left some comments with small suggestions but most are quite small, up to you if you want to make changes. Let me know and I will approve.

2021-04-02 08:18 UTC, taylorharvey-r3 approved these changes
LGTM

2021-04-06 20:22 UTC, farm requested changes

2021-04-07 07:36 UTC, erinpking approved these changes

2021-04-07 07:36 UTC, merged