Doc-427: Updated the sub-zones file for CENM 1.3, 1.4, and 1.5
corda/corda-docs pull request #424
Opened 2021-03-11 15:03 UTC by AnnaK-R3

2021-03-12 14:40 UTC, jmacmahonr3 requested changes
Hey 
The changes to the text look great. 
The only change request i'd like to see is that the signer needs to be within the compatibility zone. In the two sub zone diagrams

2021-03-16 14:39 UTC, taylorharvey-r3 reviewed
Overall looks good, just a few comments that you can take or leave.

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.3/sub-zones.md
> +From the perspective of a node a network is defined by the Identity Manager and Network Map services it is configured
```suggestion
From the perspective of a node, a network is defined by the Identity Manager and Network Map services it is configured
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.3/sub-zones.md
> +The node is unaware of other subzones, seeing only those nodes registered with the Network Map service it itself has
```suggestion
The node is unaware of other subzones - it sees only those nodes registered with the Network Map service that it has also
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.3/sub-zones.md
>  registered with.
```suggestion
registered with itself.
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.3/sub-zones.md
>  registered with.
Tried to reword this sentence to make it a bit clearer.

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.3/sub-zones.md
> +The important part from the perspective of the CENM is that the signed node info
```suggestion
The important part from the perspective of CENM is that the signed node info
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.4/sub-zones.md
> +From the perspective of a node a network is defined by the Identity Manager and Network Map services it is configured
```suggestion
From the perspective of a node, a network is defined by the Identity Manager and Network Map services it is configured
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.4/sub-zones.md
> +The node is unaware of other subzones, seeing only those nodes registered with the Network Map service it itself has
```suggestion
The node is unaware of other subzones - it sees only those nodes registered with the Network Map service that it has also
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.4/sub-zones.md
>  registered with.
```suggestion
registered with itself.
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.4/sub-zones.md
> +The important part from the perspective of the CENM is that the signed node info
```suggestion
The important part from the perspective of CENM is that the signed node info
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.5/sub-zones.md
> +From the perspective of a node a network is defined by the Identity Manager and Network Map services it is configured
```suggestion
From the perspective of a node, a network is defined by the Identity Manager and Network Map services it is configured
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.5/sub-zones.md
> +The node is unaware of other subzones, seeing only those nodes registered with the Network Map service it itself has
```suggestion
The node is unaware of other subzones - it sees only those nodes registered with the Network Map service that it has also
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.5/sub-zones.md
>  registered with.
```suggestion
registered with itself.
```

2021-03-16 14:39 UTC, taylorharvey-r3 commented on content/en/docs/cenm/1.5/sub-zones.md
> +The important part from the perspective of the CENM is that the signed node info
```suggestion
The important part from the perspective of CENM is that the signed node info
```

2021-03-16 15:35 UTC, taylorharvey-r3 approved these changes
LGTM

2021-03-16 15:45 UTC, merged