DOC-510: Added Testnet decommission page
corda/corda-docs pull request #426
Opened 2021-03-15 19:38 UTC by taylorharvey-r3

2021-03-16 10:10 UTC, taylorharvey-r3 commented
Adding a do not merge label pending publication date confirmation by Tiffany.

2021-03-18 07:47 UTC, ivanterziev-r3 requested changes
All looking good, just added fixes for the CE links to bootstrapper page

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/network/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.6/network/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/network/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.4/network/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.3/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.2/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.1/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 07:47 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.0/corda-testnet-decommission.md
> +* [**Network Bootstrapper**](network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform
```suggestion
* [**Network Bootstrapper**](../network-bootstrapper.md): An easy and flexible free tool for developers who are new to Corda. With Network Bootstrapper, you can set up remote nodes on any cloud platform.
```

2021-03-18 11:37 UTC, ivanterziev-r3 approved these changes
LGTM

2021-03-18 11:45 UTC, merged