DOC-1903: updated app-upgrade-notes, checkpoint-tooling, and app-upgrade-notes-…
corda/corda-docs pull request #434
Opened 2021-03-23 17:26 UTC by erinpking

…enterprise for versions 4.6 through 4.7 in OS and Enterprise

2021-03-23 17:33 UTC, castben commented
It looks ok to me

2021-03-23 17:36 UTC, chrisr3 commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
Isn't this for Corda 4.4? (Because a line says `corda_release_version = '4.4'` above it.) In which case, Quasar 0.7.12_r3 would be correct. Could this be a "before" view?

2021-03-23 17:37 UTC, chrisr3 commented on content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
Again, I don't understand why you have changed this line when `corda_release_version = '4.4'`. All of these values look valid for Corda 4.4. What are the notes saying here? Perhaps "When upgrading from 4.4 to 4.6, your initial properties will look like these..."?

2021-03-23 17:40 UTC, chrisr3 commented on content/en/docs/corda-enterprise/4.6/checkpoint-tooling.md
> +0.7.13_r3
Why is this number here? It doesn't follow from the sentence above :thinking:.

2021-03-23 17:41 UTC, chrisr3 commented on content/en/docs/corda-enterprise/4.7/app-upgrade-notes-enterprise.md
> +0.7.13_r3
I don't understand this change either.

2021-03-23 17:44 UTC, chrisr3 commented on content/en/docs/corda-enterprise/4.7/checkpoint-tooling.md
> +0.7.13_r3
I still don't understand this change. (Or the sentence above it.)

2021-03-23 17:44 UTC, chrisr3 commented on content/en/docs/corda-os/4.6/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
Ditto. This looks valid for Corda 4.4.

2021-03-23 17:46 UTC, chrisr3 commented on content/en/docs/corda-os/4.6/checkpoint-tooling.md
> +	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.13_r3-jdk8.jar:0.7.13_r3]
The file name is actually `quasar-core-0.7.13_r3.jar` for Quasar 0.7.13_r3. (I am also worried that you are altering a stack trace here. I cannot guarantee that the trace is valid for Quasar 0.7.13_r3.)

The filename problem is repeated in several lines.

2021-03-23 17:51 UTC, chrisr3 commented on content/en/docs/corda-os/4.7/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
When upgrading from Corda 4.4 to 4.7, the `quasar_version` will _initially_ be `0.7.12_r3'.

2021-03-23 17:53 UTC, chrisr3 commented on content/en/docs/corda-os/4.7/checkpoint-tooling.md
> +	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.13_r3-jdk8.jar:0.7.13_r3]
Same as before: this stack trace was originally created for Quasar 0.7.12_r3 and may not be valid for Quasar 0.7.13_r3. However, the correct filename for 0.7.13_r3 is `quasar-core-0.7.13_r3.jar`.

This error is repeated on multiple lines.

2021-03-23 18:01 UTC, ivanterziev-r3 requested changes
Hey @erinpking I may have got it completely wrong but I think a lot of the edits actually need to be reverted. As mentioned in the Jira ticket - we need to be careful which versions we upgrade depending on the doc section these are in, some of the upgrade pages contain historical sections for older versions so the Quasar versions in these must remain the old ones.

2021-03-23 18:01 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.7/app-upgrade-notes.md
> +* Upgrade your `quasar.jar` to `0.7.13_r3`
See comment for OS 4.6 above

2021-03-23 18:32 UTC, erinpking commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
Correct - this section of the doc is referring to the 4.4 version. I have reverted it. Would you mind pointing out the line that requires the Quasar version update change? Thanks!

2021-03-23 18:53 UTC, erinpking commented on content/en/docs/corda-enterprise/4.7/checkpoint-tooling.md
> +0.7.13_r3
Good spot - updated truncated section from OS docs per your discovery & replaced mentions of 0.7.12_r3 in the code sample.

2021-03-23 18:55 UTC, erinpking commented on content/en/docs/corda-enterprise/4.7/checkpoint-tooling.md
> +0.7.13_r3
It appears at some point in the past this sentence was truncated in the Enterprise version - I have updated it with content from the OS version. Unfortunately replace-all failed me and the new version ended up at the bottom of the doc instead of inside the code sample - lesson learned!

2021-03-24 08:40 UTC, erinpking commented on content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
Correct - reverted

2021-03-24 08:46 UTC, erinpking commented on content/en/docs/corda-os/4.6/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
correct - reverted.

2021-03-24 11:54 UTC, erinpking commented on content/en/docs/corda-os/4.6/checkpoint-tooling.md
> +	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.13_r3-jdk8.jar:0.7.13_r3]
Update - Dan has confirmed that we can scrap the stack track from the example entirely.

2021-03-24 11:54 UTC, erinpking commented on content/en/docs/corda-os/4.7/checkpoint-tooling.md
> +	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.13_r3-jdk8.jar:0.7.13_r3]
I made the same change here as in the 4.6 doc: removed the stack trace example and references to the example.

2021-03-24 11:58 UTC, erinpking commented on content/en/docs/corda-enterprise/4.7/app-upgrade-notes.md
> +ext.quasar_version = '0.7.13_r3'
reverted to 0.7.12_r3

2021-03-24 11:59 UTC, erinpking commented on content/en/docs/corda-enterprise/4.6/checkpoint-tooling.md
> +0.7.13_r3
Added to code sample and added end of truncated sample from OS version.

2021-03-24 11:59 UTC, erinpking commented on content/en/docs/corda-enterprise/4.7/app-upgrade-notes-enterprise.md
> +0.7.13_r3
Same change as above, per Ivan's comments.

2021-03-24 12:10 UTC, erinpking reviewed
I think I have resolved all of these - please let me know if I haven't.

2021-03-24 12:11 UTC, erinpking commented on content/en/docs/corda-os/4.7/app-upgrade-notes.md
> +* Upgrade your `quasar.jar` to `0.7.13_r3`
reverted.

2021-03-24 12:37 UTC, erinpking reviewed
Additional changes to remove the stack trace example from Enterprise versions.

2021-03-24 19:03 UTC, ivanterziev-r3 approved these changes
These changes look good. 
We need to also add sub-sections about quasar to the CE 4.6 and 4.7 app-upgrade-notes.md  pages but this can be done in a separate Jira/branch/PR.

2021-03-25 11:32 UTC, merged