DOC-1794 and DOC-1832 - Archive/LedgerGraph updates/release notes
corda/corda-docs pull request #435
Opened 2021-03-24 16:11 UTC by benpesterr3

release note and doc updates for patch release 4.7.1

2021-04-19 15:26 UTC, ivanterziev-r3 commented
Hi @relyafi  and @jamesbr3 , can you please review the notary fix doc changes in this commit 1a6516f03cb36eaa23877e5dba1fe6b9b2ab2209

2021-04-19 16:32 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +Run the ledger health check tool before accepting the Corda Enterprise 4.3.7 patch release to detect whether your notary cluster has been affected.
needs a link or some sort of guidance how to get this tool (e.g. if it's i the release pack artifacts, how is it called etc.)

2021-04-19 16:32 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +This release addresses a security issue in the JPA notary if the Corda database management tool was used during notary backing database setup. Corda implementations that do not use the Corda database
add link to the db management tool page

2021-04-19 16:37 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +This release addresses a security issue in the JPA notary if the Corda database management tool was used during notary backing database setup. Corda implementations that do not use the Corda database
also the capitalisation of the db management tool is not consistent across the section - although this is the case with the actual db management tool page itself

2021-04-20 08:03 UTC, edward-prosser commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +This release addresses a security issue in the JPA notary if the Corda database management tool was used during notary backing database setup. Corda implementations that do not use the Corda database
Good point, had forgotten that one.

2021-04-20 08:29 UTC, relyafi reviewed
As the content is duplicated across a number of patches, I've only commented against one version, but the comments apply to all versions.

2021-04-20 08:29 UTC, relyafi commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes-enterprise.md
> +Corda Enterprise 4.3.7 fixes a key security vulnerability. Before upgrading to Corda Enterprise 4.3.7 please read the guidance on [upgrading your notary service](running-a-notary-cluster/upgrading-th
Should this read "key security vulnerability **in the JPA notary**"? As it stands, I'd immediately worry as a Corda node operator that I have a serious security issue, and the fact it's notary specific is only implied from the link at the end.

(Also applies to the copy / pastes in other files)

2021-04-20 08:29 UTC, relyafi commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +Run the ledger health check tool before accepting the Corda Enterprise 4.3.7 patch release to detect whether your notary cluster has been affected.
Is this the right place to be documenting this? We are not shipping this tool as part of Corda.

2021-04-20 08:29 UTC, relyafi commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +The ledger health check tool should be run on one of the notary workers in your notary cluster while the notary cluster is running. If the tool is being run in the base directory of the notary worker
As above - we're providing instructions for running a tool that won't be available to customers unless they contact support.

2021-04-20 08:29 UTC, relyafi commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +After accepting the 4.3.7 patch, you must re-run the Corda Database Management Tool to apply the security fix.
What do we mean by "accepting"? That sounds odd to me. Did you mean "applying"? That's the terminology used in the previous sentence.

2021-04-20 08:35 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +The ledger health check tool should be run on one of the notary workers in your notary cluster while the notary cluster is running. If the tool is being run in the base directory of the notary worker
@relyafi  This is not what I thought - my understanding was that we would provide the tool as part of the release pack for each patch, and all customers would be required to run the tool prior to starting the patch upgrade. Perhaps I've misunderstood?

2021-04-20 14:30 UTC, jamesbr3 requested changes
see inline comment; same treatment for other occurances

2021-04-20 14:30 UTC, jamesbr3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes-enterprise.md
> +Corda Enterprise 4.3.7 fixes a key security vulnerability. Before upgrading to Corda Enterprise 4.3.7 please read the guidance on [upgrading your notary service](running-a-notary-cluster/upgrading-th
I would change this slightly - suggest 'Corda Enterprise X.Y.Z fixes a vulnerability in...' 

i.e. remove the 'key' part, and either qualify it with the word 'critical' or omit the qualifier  entirely

2021-04-21 08:09 UTC, relyafi commented
Notary changes LGTM

2021-04-21 08:09 UTC, relyafi approved these changes

2021-04-21 10:57 UTC, ivanterziev-r3 commented
@jamesbr3  Can you review again please?

2021-04-21 13:56 UTC, jamesbr3 approved these changes
LGTM

2021-04-22 16:28 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes-enterprise.md
> +{{<warning>}}
Question. Do the {{<warning>}} tags work with no spaces?

2021-04-22 16:28 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes-enterprise.md
> +{{<warning>}}
I would usually type it as {{< warning >}}

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes-enterprise.md
> +{{</warning>}}
Same comment as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes.md
> +{{<warning>}}
Same comment as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/app-upgrade-notes.md
> +{{</warning>}}
Same comment as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +{{<warning>}}
Same comment as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.3/running-a-notary-cluster/upgrading-the-ha-notary-service.md
> +{{</warning>}}
Same as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/app-upgrade-notes-enterprise.md
> +{{<warning>}}
Same comment as above.

2021-04-22 16:29 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/app-upgrade-notes-enterprise.md
> +{{</warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
> +{{<warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/app-upgrade-notes.md
> +{{</warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/database-management-tool.md
> +{{<warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/database-management-tool.md
> +{{</warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/node-upgrade-notes.md
> +{{<warning>}}
Same as above.

2021-04-22 16:30 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/node-upgrade-notes.md
> +{{</warning>}}
Same as above.

2021-04-22 16:31 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/notary/upgrading-the-ha-notary-service.md
> +{{<warning>}}
Same as above.

2021-04-22 16:31 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/notary/upgrading-the-ha-notary-service.md
> +{{</warning>}}
Same as above.

2021-04-22 16:32 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/app-upgrade-notes-enterprise.md
> +{{<warning>}}
Same as above.

2021-04-22 16:33 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/app-upgrade-notes-enterprise.md
> +{{</warning>}}
Same as above.

2021-04-22 16:33 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
> +{{<warning>}}
Same as above.

2021-04-22 16:33 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/app-upgrade-notes.md
> +{{</warning>}}
Same as above.

2021-04-22 16:33 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/database-management-tool.md
> +{{<warning>}}
Same as above.

2021-04-22 16:33 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/database-management-tool.md
> +{{</warning>}}
Same as above.

2021-04-22 16:34 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/legal-info-4.5.3.md
> +
Looks like this was an accidental change? Or was something new supposed to be added here?

2021-04-22 16:34 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/node-upgrade-notes.md
> +{{<warning>}}
Same as above.

2021-04-22 16:34 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/node-upgrade-notes.md
> +{{</warning>}}
Same as above.

2021-04-22 16:35 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/notary/upgrading-the-ha-notary-service.md
> +{{</warning>}}
Same as above.

2021-04-22 16:35 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
> +{{<warning>}}
Same as above.

2021-04-22 16:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes-enterprise.md
> +{{</warning>}}
Same as above.

2021-04-22 16:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
> +{{<warning>}}
Same as above.

2021-04-22 16:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/app-upgrade-notes.md
> +{{</warning>}}
Same as above.

2021-04-22 16:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/database-management-tool.md
> +{{<warning>}}
Same as above.

2021-04-22 16:36 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/database-management-tool.md
> +{{</warning>}}
Same as above.

2021-04-22 16:38 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.6/node-upgrade-notes.md
> +{{<warning>}}
I won't leave more comments (there's already a ton oops) but `{{<warning>}}` is typed consistently throughout and I think it's incorrect.

2021-04-22 16:40 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/legal-info-4.5.3.md
> +
It's fine, this is a removed extra line in the frontmatter (correctly) and an added new line after that section

2021-04-22 16:41 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.7/release-checksum-enterprise.md
> +## Corda Entperprise 4.7.1 release files and checksums
```suggestion
## Corda Enterprise 4.7.1 release files and checksums
```

2021-04-22 17:34 UTC, taylorharvey-r3 approved these changes
LGTM

2021-04-22 18:23 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/node/operating/cryptoservice-configuration.md
> +1. `cloudhsm-3.1.2.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```suggestion
1. `cloudhsm-3.2.1.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```

2021-04-22 18:24 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/operations/deployment/cenm-deployment.md
> +|AWS CloudHSM|N/A|3.1.2|No|
```suggestion
|AWS CloudHSM|N/A|3.2.1|No|
```

2021-04-22 18:25 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/operations/deployment/hsm-deployment.md
> +1. `cloudhsm-3.1.2.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```suggestion
1. `cloudhsm-3.2.1.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```

2021-04-22 18:25 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/operations/project-planner/network-operators.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | Not supported            |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | Not supported            |
```

2021-04-22 18:25 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/operations/project-planner/node-operator.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | Not supported            |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | Not supported            |
```

2021-04-22 18:26 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/pki-tool.md
> +    jars = ["/opt/cloudhsm/java/cloudhsm-3.1.2.jar"]
```suggestion
    jars = ["/opt/cloudhsm/java/cloudhsm-3.2.1.jar"]
```

2021-04-22 18:27 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/platform-support-matrix.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2      |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1      |
```

2021-04-22 18:28 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.5/release-notes-enterprise.md
> +Corda Enterprise 4.5.3 is a patch release of Corda Enterprise that introduces fixes to known issues in Corda Enterprise 4.5.2.
```suggestion
Corda Enterprise 4.5.3 is a patch release of Corda Enterprise that introduces fixes to known issues in Corda Enterprise 4.5.2.

### Upgrade recommendation

As a developer, you should upgrade to the [latest released version of Corda](https://docs.corda.net/docs/corda-enterprise/index.html) as soon as possible. Check the latest Corda Enterprise release notes and upgrade guide [here](https://docs.corda.net/docs/corda-enterprise/release-notes-enterprise.html).
As a node operator, you should upgrade to the [latest released version of Corda](https://docs.corda.net/docs/corda-enterprise/index.html) if the fixed issues listed below are relevant to your work.

```

2021-04-22 18:31 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.6/operations/deployment/hsm-deployment.md
> +1. `cloudhsm-3.1.2.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```suggestion
1. `cloudhsm-3.2.1.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```

2021-04-22 18:32 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.6/operations/project-planner/network-operators.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | Not supported            |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | Not supported            |
```

2021-04-22 18:33 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.6/pki-tool.md
> +    jars = ["/opt/cloudhsm/java/cloudhsm-3.1.2.jar"]
```suggestion
    jars = ["/opt/cloudhsm/java/cloudhsm-3.2.1.jar"]
```

2021-04-22 18:34 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.6/platform-support-matrix.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2      |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1      |
```

2021-04-22 18:37 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/node/operating/cryptoservice-configuration.md
> +1. `cloudhsm-3.1.2.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```suggestion
1. `cloudhsm-3.2.1.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```

2021-04-22 18:37 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/node/operating/ledger-graph.md
> +**onDemand**: In V1.2.1 you can configure the setting 'onDemand' to 'true' or 'false'. When set to 'true', your LedgerGraph becomes an on-demand service, active only when triggered by the [Archive Se
```suggestion
**onDemand**: In V1.2.1 you can configure the setting `onDemand` to `true` or `false`. When set to `true`, your LedgerGraph becomes an on-demand service, active only when triggered by the [Archive Service](../archiving/archiving-setup.md). This saves heap memory usage.
```

2021-04-22 18:39 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/node/operating/ledger-graph.md
> +|`onDemand`|`true`| `true`, `false`|When onDemand is set to `true`, LedgerGraph does not
```suggestion
|`onDemand`|`true`| `true`, `false`|When set to `true`, your LedgerGraph becomes an on-demand service, active only when triggered by the [Archive Service](../archiving/archiving-setup.md). This saves heap memory usage.
```

2021-04-22 18:40 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/operations/deployment/cenm-deployment.md
> +|AWS CloudHSM|N/A|3.1.2|No|
```suggestion
|AWS CloudHSM|N/A|3.2.1|No|
```

2021-04-22 18:41 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/operations/deployment/hsm-deployment.md
> +1. `cloudhsm-3.1.2.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```suggestion
1. `cloudhsm-3.2.1.jar` from AWS CloudHSM Software Library for Java needs to be placed in the node’s `drivers` folder.
```

2021-04-22 18:41 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/operations/project-planner/network-operators.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2      |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1      |
```

2021-04-22 18:42 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/operations/project-planner/node-operator.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2      |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1      |
```

2021-04-22 18:42 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/pki-tool.md
> +    jars = ["/opt/cloudhsm/java/cloudhsm-3.1.2.jar"]
```suggestion
    jars = ["/opt/cloudhsm/java/cloudhsm-3.2.1.jar"]
```

2021-04-22 18:42 UTC, ivanterziev-r3 commented on content/en/docs/corda-enterprise/4.7/platform-support-matrix.md
> +| AWS CloudHSM                  | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2     | * Driver version 3.1.2      |
```suggestion
| AWS CloudHSM                  | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1     | * Driver version 3.2.1      |
```

2021-04-22 18:53 UTC, ivanterziev-r3 approved these changes
LGTM

2021-04-22 18:56 UTC, merged