DOC-144: initial update to add kubernetes dashboard
corda/corda-docs pull request #436
Opened 2021-03-24 16:28 UTC by AMcFarlandCampbellR3

This is a complicated issue: please see https://r3-cev.atlassian.net/browse/DOC-144 for detail.

2021-03-30 14:11 UTC, przemolb commented
I cannot update https://r3-cev.atlassian.net/browse/DOC-144 so will add my comment here: the kubernetes dashboard is not needed at all to deploy CENM. It may trick users and they will start asking why it is needed.
During my development work on CENM/K8s deployment I have **never** used kubernetes dashboard.
I would recommend removing this section unless there is technical justification to use it.

2021-04-01 07:40 UTC, AMcFarlandCampbellR3 commented
I have updated the PR following discussion on Jira.

2021-04-01 16:13 UTC, szymonsztuka requested changes

2021-04-01 16:13 UTC, szymonsztuka commented on content/en/docs/cenm/1.5/deployment-kubernetes.md
> +You may also want to install the Kubernetes dashboard, but this is not required. To install the Kubernetes dashboard, run the following commands from the `network-services/deployment/k8s/helm` direct
This is probably in wrong place, how optional Kubernetes dashboard relates to `## Manual bootstrap` ?
Does it mean that it can't be run for "automatic CENm Deployment"?
What is Kubernetes dashboard for, is it R3 software ?
I'm guessing if a customer knows K8s Dashboard then he doesn't need this part, if customer doesn't know about Kuebrnetes dashboard then this is just confusing.

2021-04-02 07:15 UTC, AMcFarlandCampbellR3 commented on content/en/docs/cenm/1.5/deployment-kubernetes.md
> +You may also want to install the Kubernetes dashboard, but this is not required. To install the Kubernetes dashboard, run the following commands from the `network-services/deployment/k8s/helm` direct
I think this needs a call to discuss exactly what changes are needed. I will set one up.

2021-04-02 07:26 UTC, przemolb commented on content/en/docs/cenm/1.5/deployment-kubernetes.md
> +You may also want to install the Kubernetes dashboard, but this is not required. To install the Kubernetes dashboard, run the following commands from the `network-services/deployment/k8s/helm` direct
I fully agree with @szymonsztuka comment.

2021-04-09 14:26 UTC, AMcFarlandCampbellR3 commented on content/en/docs/cenm/1.5/deployment-kubernetes.md
> +You may also want to install the Kubernetes dashboard, but this is not required. To install the Kubernetes dashboard, run the following commands from the `network-services/deployment/k8s/helm` direct
Removed, following call on 2021-04-08

2021-04-09 14:54 UTC, AnnaK-R3 submitted a review, later dismissed

2021-07-27 09:56 UTC, taylorharvey-r3 approved these changes
LGTM

2021-07-27 10:01 UTC, merged