DOC-1884 updates to file tutorial-cordapp
corda/corda-docs pull request #438
Opened 2021-03-26 14:43 UTC by erinpking

Changes just to the OS 4.7 and 4.6 versions for now - will propagate to versions 4.0+ in CE +OS once changes are approved.

Updates to 'Running a Sample Cordapp' to reflect changes to the sample code. 
- Remove all references to Party C. 
- Remove step to specify JDK in intelliJ as this is done automatically. 
- Remove step to manually import Gradle module as this is done automatically
- Update launch commands to reflect code changes
- Update curl command to reflect code changes
- Remove instructions for submitting an IOU via the web front end - no longer works in the sample and has been deemed too advanced for this tutorial.
- Added more detailed instructions for running the tests and reordered to fit natural testing flow
- Added a section on debugging tests

2021-03-29 11:11 UTC, taylorharvey-r3 requested changes
Some suggested changes and some questions. Let me know if anything is unclear!

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
>  ```
I can't leave a comment there because you didn't change the section, but there's a line above (under Via HTTP) that says "There is also a web front-end served from the home web page e.g. `localhost:50005`." 
If the front end if no longer in use, this line should be removed.

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +1. Go to Workflows > src > IntegrationTest > DriverBasedTest.
```suggestion
1. Go to `Workflows` > `src` > `IntegrationTest` > `DriverBasedTest`.
```

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +1. Go to Workflow > src > test > ContractTests.
```suggestion
1. Go to `Workflow` > `src` > `test` > `ContractTests`.
```

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +1. Go to Workflow > src > test > FlowTests.
```suggestion
1. Go to `Workflow` > `src` > `test` > `FlowTests`.
```

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +1. Open the *Gradle* tab on the right-hand side of your IntelliJ window.
```suggestion
1. Open the **Gradle** tab on the right-hand side of your IntelliJ window.
```
I think we use bold for screen elements in UIs.

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +2. Open *Build Tool Settings* (wrench icon) and select ‘Gradle Settings’.
Same as above, look at these for all steps.

2021-03-29 11:11 UTC, taylorharvey-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +5. Delete the unit test driver and *Apply*.
```suggestion
5. Delete the unit test driver and click **Apply**.
```

2021-03-29 13:27 UTC, erinpking commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
> +1. Go to Workflow > src > test > FlowTests.
I had been wondering what our formatting preferences were for file paths...! :)

2021-03-31 17:58 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
>  ### Project structure
I am not sure if this is really necessary tho. 🤔

2021-04-09 14:23 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
yes, get rid of partyC

2021-04-09 14:23 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
yes, dont worry about SDKs.

2021-04-09 14:27 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
line 342 ~ 345: get rid of the [/api/example] it is just "/me' & "/peers"

2021-04-09 14:29 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
>  ### Via the interactive shell (terminal only)
line 389, 
change 
com.example.flow.ExampleFlow$Initiator
to 
net.corda.samples.example.flows.ExampleFlow$Initiator

2021-04-09 14:30 UTC, peterli-r3 commented on content/en/docs/corda-os/4.6/tutorial-cordapp.md
line 360 same

2021-04-12 17:25 UTC, taylorharvey-r3 approved these changes
LGTM!

2021-04-26 14:07 UTC, taylorharvey-r3 reviewed
Overall looks great! Just a few minor comments (most comments made in CE 4.4 file but same comments apply across versions).

2021-04-26 14:07 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
> +Corda provides several frameworks for writing unit and integration tests for CorDapps. To access test flows in IntelliJ, select an option from the ‘Run Configurations’ dropdown next to the hammer ico
Also did you build locally and test this link? The format looks odd to me but that might just be because it's Monday. :)

2021-04-26 14:07 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.4/cordapps/tutorial-cordapp.md
> +2. Select the arrow next to the test code. Choose the arrow at the top to run all the tests at once, or select the arrow next to a particular section to test it individually.
```suggestion
2. Select the **arrow** next to the test code. Choose the arrow at the top to run all the tests at once, or select the arrow next to a particular section to test it individually.
```

2021-04-26 14:07 UTC, taylorharvey-r3 commented on content/en/docs/corda-enterprise/4.5/cordapps/tutorial-cordapp.md
> +Because data is only propagated on a need-to-know basis, any IOUs agreed between PartyA and PartyB become “shared facts” between PartyA and PartyB only.
```suggestion
Because data is only propagated on a need-to-know basis, any IOUs agreed between **PartyA** and **PartyB** become “shared facts” between **PartyA** and **PartyB** only.
```
I think these are bolded in some places in these files and not others. It could go either way I think, but should be consistent.

2021-04-26 14:39 UTC, taylorharvey-r3 approved these changes
LGTM

2021-04-26 14:40 UTC, merged