DOC-120: Update Corda PV page to reflect changes from v4.4 on
corda/corda-docs pull request #454
Opened 2021-04-20 14:31 UTC by erinpking

2021-04-27 12:42 UTC, AnnaK-R3 approved these changes

2021-04-28 06:27 UTC, ivanterziev-r3 approved these changes
LGTM

2021-04-28 06:39 UTC, ivanterziev-r3 requested changes
Some bad placing of table tags causing the build to fail - comments added.

2021-04-28 06:39 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.6/features-versions.md
>  {{< /table >}}
@erinking-r3  Please move the closing table tag above the note as this is causing the build to fail.

2021-04-28 06:39 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.8/features-versions.md
>  {{< /table >}}
Remove the last table tag it's redundant and is causing the build to fail

2021-04-28 06:39 UTC, ivanterziev-r3 commented on content/en/docs/corda-os/4.5/features-versions.md
>  {{< /table >}}
@erinking-r3 Please move the closing table tag above the note as this is causing the build to fail.

2021-04-28 08:06 UTC, erinking-r3 commented on content/en/docs/corda-os/4.5/features-versions.md
>  {{< /table >}}
```suggestion
|New Flow Framework APIs|7|4|4.5|4.5|
{{< /table >}}

{{< note >}}
We recommend a minimum network platform version of 5 for Corda 4.5; however, a network mPV of 4 may continue to work in some instances.
{{< /note >}}

```

2021-04-28 08:06 UTC, erinking-r3 commented on content/en/docs/corda-os/4.6/features-versions.md
>  {{< /table >}}
```suggestion
|API Update|8|4|4.6|4.6|
{{< /table >}}

{{< note >}}
We recommend a minimum network platform version of 5 for Corda 4.5 onwards; however, a network mPV of 4 may continue to work in some instances.
{{< /note >}}

```

2021-04-28 08:06 UTC, erinking-r3 commented on content/en/docs/corda-os/4.8/features-versions.md
>  {{< /table >}}
```suggestion
{{< /note >}}

```

2021-04-28 08:38 UTC, ivanterziev-r3 approved these changes
LGTM

2021-04-28 09:18 UTC, merged